# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43fc483f35877e99adb12dddeeca62acc093e8fe40b242655ad60b11739490a4ff144ebd452fdc4eef85f1f80e4f52283af812bfd2a79d5f54c06dcdc1e94aea

test:
  secret_key_base: 7242f270ebb66b71246248ba00019f5cfbf3095e0d374e8cbd9ffb95f4af66668629b7282ac8502640cbc1a6e3bdedb400a1a3d2006056d7dd96ca10ca1c9677

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
